import axios from 'axios';
import Head from 'next/head';
import Header from '../components/Header';
import Hero from '../components/Hero';
import Latest from '../components/Latest';

export default function Home({ results }) {
  console.log(results);
  return (
    <div>
      <Head>
        <title>SmartCodeTest</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Hero />
      <Latest />
    </div>
  );
}

export async function getServerSideProps(context) {
  //const genre = context.query;

  const res = await axios.post(
    'http://eventregistry.org/api/v1/article/getArticles',
    {
      action: 'getArticles',
      keyword: 'Barack Obama',
      articlesPage: 1,
      articlesCount: 100,
      articlesSortBy: 'date',
      articlesSortByAsc: false,
      articlesArticleBodyLen: -1,
      resultType: 'articles',
      dataType: ['news', 'pr'],
      apiKey: '0f854066-6c1a-4d17-be7a-82f74a68cb52',
      forceMaxDataTimeWindow: 31,
    },
  );

  if (!res) {
    return {
      notFound: true,
    };
  }

  return {
    props: {
      results: res.data,
    },
  };
}
