import Head from 'next/head';
import Header from '../components/Header';
import Hero from '../components/Hero';
import Latest from '../components/Latest';
import { fetchArticles } from '../utils/requests';

export default function Home({ results }) {
  console.log(results);
  return (
    <div>
      <Head>
        <title>SmartCodeTest</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Hero />
      <Latest />
    </div>
  );
}

export async function getServerSideProps() {
  const res = await fetchArticles();

  if (!res) {
    return {
      notFound: true,
    };
  }

  return {
    props: {
      results: res.data,
    },
  };
}
